[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[aws]
bucket='umerghani-aws-wcd-lab'
folder='input/'

[db]
host='aws-superstore-db.cs4mayiuqhbl.ca-central-1.rds.amazonaws.com'
port=3306
database='superstore'
username='admin'
password='pFr124hm!'




    

    